ecosystem:
  main_project: optaplanner
  projects:
  - name: optaplanner
    regexs:
    - opta.*
  - name: kie-benchmarks
    ignore_release: true
    regexs:
    - kie-benchmarks.*
git:
  branches:
  - name: apache_migration
    main_branch: true
seed:
  config_file:
    git:
      repository: optaplanner
      author:
        name: kiegroup
        credentials_id: kie-ci5
      branch: apache_migration
    path: .ci/jenkins/config/branch.yaml
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
